=begin
#HLS Conversion batch controller

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for HlsApiClient::ConversionControllerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ConversionControllerApi' do
  before do
    # run before each test
    @api_instance = HlsApiClient::ConversionControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConversionControllerApi' do
    it 'should create an instance of ConversionControllerApi' do
      expect(@api_instance).to be_instance_of(HlsApiClient::ConversionControllerApi)
    end
  end

  # unit tests for callback_echo
  # Do-nothing, replies with the input; this exists just facilitate using the CallbackConvert datatype to receive callbacks
  # @param convert_callback 
  # @param [Hash] opts the optional parameters
  # @return [ConvertCallback]
  describe 'callback_echo test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for convert
  # Start a conversion job
  # @param convert_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'convert test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_job_results
  # Delete artifacts from a given job
  # @param delete_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_job_results test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
