=begin
#HLS Conversion batch controller

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for HlsApiClient::ConvertCallback
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe HlsApiClient::ConvertCallback do
  let(:instance) { HlsApiClient::ConvertCallback.new }

  describe 'test an instance of ConvertCallback' do
    it 'should create an instance of ConvertCallback' do
      expect(instance).to be_instance_of(HlsApiClient::ConvertCallback)
    end
  end
  describe 'test attribute "job_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "result"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["CREATING", "INPUT_READ", "INPUT_WRITTEN", "STARTED", "FAILED", "SUCCESS"])
      # validator.allowable_values.each do |value|
      #   expect { instance.result = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "version"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "encoding_profile"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
