=begin
#HLS Conversion batch controller

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for HlsApiClient::DeleteRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe HlsApiClient::DeleteRequest do
  let(:instance) { HlsApiClient::DeleteRequest.new }

  describe 'test an instance of DeleteRequest' do
    it 'should create an instance of DeleteRequest' do
      expect(instance).to be_instance_of(HlsApiClient::DeleteRequest)
    end
  end
  describe 'test attribute "api_token"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "job_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
