=begin
#HLS Conversion batch controller

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

# Common files
require 'hls_api_client/api_client'
require 'hls_api_client/api_error'
require 'hls_api_client/version'
require 'hls_api_client/configuration'

# Models
require 'hls_api_client/models/convert_callback'
require 'hls_api_client/models/convert_request'
require 'hls_api_client/models/delete_request'

# APIs
require 'hls_api_client/api/conversion_controller_api'

module HlsApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   HlsApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
