=begin
#HLS Conversion batch controller

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

module HlsApiClient
  VERSION = '0.1.0'
end
